#!/bin/bash

ARGV=( \
	reason=$reason \
	interface="$interface" \
	medium="$medium" \
)

for var in ${!new_*} ${!old_*} ${!alias_*} routers; do
	ARGV+=($var="${!var}")
done

runevent dhclient-exit-hooks "${ARGV[@]}" & disown
